### ISSUE TITLE
(Bug) Fix event processing

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-dapps-voting#124]
![2018-04-20 13 55 18](https://user-images.githubusercontent.com/9360827/39073456-b36a9044-44a2-11e8-9128-dc5f8f452ea6.gif)
seems like there is wrong way of going thru all events and store is doing life updates  on the fly

**Comment by varasev** [comment]
@rstormsf could you please write a few steps to reproduce it - it's not clear enough what's wrong on your gif.

**Comment by varasev** [comment]
@rstormsf sorry, I got it.

**Comment by varasev** [comment]
This is an example of how slowly the tabs switch:

![screen](https://user-images.githubusercontent.com/33550681/39464989-66c7459a-4d29-11e8-9a96-ae8404b3a0e3.gif)

The reason is that every time we click on the tab the data re-downloaded from smart contracts again.

Triggers for `BallotCard` loadings are here: https://github.com/poanetwork/poa-dapps-voting/blob/9ff2e5cbf0d35f94a4e967dfba9c12033b009ab9/src/App.js#L67

`Ballots` component is called when a URL changes: https://github.com/poanetwork/poa-dapps-voting/blob/9ff2e5cbf0d35f94a4e967dfba9c12033b009ab9/src/App.js#L13

`Ballots` component reloads ballot cards: https://github.com/poanetwork/poa-dapps-voting/blob/9ff2e5cbf0d35f94a4e967dfba9c12033b009ab9/src/components/Ballots.jsx

`BallotCard` constructor is called every time for each ballot: https://github.com/poanetwork/poa-dapps-voting/blob/9ff2e5cbf0d35f94a4e967dfba9c12033b009ab9/src/components/BallotCard.jsx#L349

I've checked that using `console.log`.

I.e. `BallotCard` reads smart contracts every time when the constructor is called. So, when we click on any tab we should wait until all of the cards are loaded.

The more ballots, the slower the load of the tab.

Firstly, I think this DApp needs to use some cache (storage in browser memory) to prevent repeatedly loading the same info from the network every time when the tab is clicked.

Secondly, this DApp will load slowly when a number of the ballots is sufficiently large. I think it is necessary to make some "Load more" function (or splitting the ballot list into pages) and load only the first 30 ballots on the start page.

**Comment by 6proof** [comment]
Consider loading ballots only 6 at a time?  Default to loading 'active' ballots?

**Comment by varasev** [comment]
Yeah, we should optimize requests to the network as it was described [here](https://github.com/poanetwork/poa-dapps-voting/issues/128) and [here](https://github.com/poanetwork/poa-network-consensus-contracts/issues/128#issuecomment-396267424).

Also, it's better to show the `Active` tab by default on the start page and add `Load more` feature to the `All` tab (displaying only the last 20 or 30 ballots on this tab).

**Comment by 6proof** [comment]
This sounds like reasonable mitigation.

**Comment by varasev** [comment]
Done in #136 and #139.
