### ISSUE TITLE
(bug) Incorrect ballot results for minimum value

### ISSUE THREAD

**Issue by rstormsf** [oraclesorg/oracles-dapps-voting#208]
The UI voting dapp shows incorrect value for minimum number of validators that was required to vote.
Example:
![image](https://user-images.githubusercontent.com/9360827/67739674-7c927e80-f9d0-11e9-81c7-cef14311b3f6.png)

it shows as 5, while it was actually 8 during the ballot.

**Comment by varasev** [comment]
Yes, the DApp displays the current `minThreshold` value for all the ballots and doesn't use `VotingTo*.getMinThresholdOfVoters` individual getter for each separate ballot. That should be fixed.

**Comment by varasev** [comment]
Done in https://github.com/poanetwork/poa-dapps-voting/pull/214. Please note, that we had to remove displaying the total number of validators in the ballot since it was incorrect (that was displaying the current total number of validators, not the number actual at the moment of ballot's finalization - the actual number for each ballot is not stored anywhere in the contracts), so now the ballot looks like this:\
\
![image](https://user-images.githubusercontent.com/33550681/71595380-5f9f3680-2b4c-11ea-9aff-7b4b3891b1e1.png)
